title: "Luca Scarpantonio"
tagline: "Data Science | Python | QA Digitalization"
description: "Portfolio & Blog — a journey through data, automation, and digital transformation."
url: "https://lucascarpantonio.github.io"
avatar: /assets/img/image.png

github:
  username: lucascarpantonio
social:
  name: Luca Scarpantonio
  links:
    - https://github.com/lucascarpantonio
    - https://www.linkedin.com/in/lucascarpantonio/

theme_mode: dark
lang: it
timezone: Europe/Rome
theme: jekyll-theme-chirpy

collections:
  tabs:
    output: true
    sort_by: order
  projects:
    output: true
    sort_by: title
    permalink: /:collection/:name

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: project
      author: Luca Scarpantonio

footer:
  custom_text: >
    © 2025 Luca Scarpantonio — Powered by Jekyll & Chirpy
    
future: true